### ISSUE TITLE
import org.andengine.entity.shape.IAreaShape; cant be resolved

### ISSUE THREAD

**Issue by nickyrabit** [nicolasgramlich/AndEnginePhysicsBox2DExtension#10]
i installed the extension andthis error ocured im a noob please help

**Comment by mmanishh** [comment]
You might have used andEngine GLES Anchor version with andEnginePhysics2DExtension GLES version.
GLES Anchor and GLES are two different version. Try using andEngine GLES version instead GLES Anchor

**Comment by nickyrabit** [comment]
thank you
